#!/usr/bin/env python3
"""Build the final judge-facing proof index after hosted verification.

This script is intentionally post-deployment only. It collects the live proof
artifacts generated by `make submission-proof`, fetches the hero evidence export
from the public deployment, and writes a compact Markdown index a judge can read
without chasing multiple JSON files first.
"""
from __future__ import annotations

import argparse
import json
import os
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT_DIR = ROOT / "artifacts"
DEFAULT_HERO_EVIDENCE = DEFAULT_ARTIFACT_DIR / "hero-evidence.json"
DEFAULT_OUTPUT = DEFAULT_ARTIFACT_DIR / "final-proof-index.md"
REQUIRED_SOCIETY_ROLES = {
    "recorder",
    "triage",
    "diagnosis",
    "safety_reviewer",
    "commander",
    "operator",
}
VALID_AUTHORIZATION_PATHS = {"StructuredApproval", "PolicyAuthorization"}


class FinalProofError(ValueError):
    """Raised when final proof artifacts are missing or insufficient."""


def _read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise FinalProofError(f"missing required artifact: {path}") from exc
    except json.JSONDecodeError as exc:
        raise FinalProofError(f"invalid JSON artifact: {path}") from exc
    if not isinstance(payload, dict):
        raise FinalProofError(f"artifact root must be an object: {path}")
    return payload


def _fetch_json(url: str) -> dict[str, Any]:
    request = urllib.request.Request(
        url,
        headers={"User-Agent": "YITING-final-proof-index/1.0"},
    )
    with urllib.request.urlopen(request, timeout=12.0) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if not isinstance(payload, dict):
        raise FinalProofError(f"URL did not return a JSON object: {url}")
    return payload


def _positive_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and value > 0


def _normalize_family(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return " ".join(value.replace("_", " ").replace("-", " ").split()).strip().lower()


def _deployment_check_names(deployment: dict[str, Any]) -> set[str]:
    checks = deployment.get("checks")
    if not isinstance(checks, list):
        return set()
    return {
        str(item.get("name", ""))
        for item in checks
        if isinstance(item, dict) and item.get("ok") is True
    }


def _validate_collaboration_block(collaboration: dict[str, Any]) -> list[str]:
    failures: list[str] = []
    required_keys = {
        "role_sequence",
        "handoff_count",
        "challenge_count",
        "human_decision_count",
        "authorization_path",
        "execution_conflict_control",
    }
    missing_keys = sorted(required_keys - set(collaboration))
    if missing_keys:
        failures.append(f"collaboration missing keys: {missing_keys}")

    role_sequence = collaboration.get("role_sequence")
    if not isinstance(role_sequence, list):
        failures.append("collaboration.role_sequence must be a list")
    else:
        missing_roles = sorted(REQUIRED_SOCIETY_ROLES - set(role_sequence))
        if missing_roles:
            failures.append(f"collaboration.role_sequence missing roles: {missing_roles}")

    handoff_count = collaboration.get("handoff_count")
    if not isinstance(handoff_count, int) or handoff_count < 5:
        failures.append("collaboration.handoff_count must be >= 5")

    counts: dict[str, int] = {}
    for key in ("challenge_count", "human_decision_count"):
        value = collaboration.get(key)
        if not isinstance(value, int) or value < 0:
            failures.append(f"collaboration.{key} must be a non-negative integer")
        else:
            counts[key] = value

    human_decisions = collaboration.get("human_decisions")
    if not isinstance(human_decisions, list):
        failures.append("collaboration.human_decisions must be a list")
        human_rejection_count = 0
    else:
        human_rejection_count = sum(
            1 for item in human_decisions
            if isinstance(item, dict) and item.get("decision") == "REJECTED"
        )

    if counts.get("challenge_count", 0) + human_rejection_count <= 0:
        failures.append(
            "hero evidence must include a sealed Verdict(CHALLENGE) or "
            "StructuredApproval(REJECTED) for Track 3 disagreement proof"
        )

    authorization_path = collaboration.get("authorization_path")
    if authorization_path not in VALID_AUTHORIZATION_PATHS:
        failures.append(
            "collaboration.authorization_path must be StructuredApproval or PolicyAuthorization"
        )
    elif authorization_path == "StructuredApproval" and counts.get("human_decision_count", 0) <= 0:
        failures.append(
            "StructuredApproval hero evidence must include at least one human decision"
        )

    conflict = collaboration.get("execution_conflict_control")
    if not isinstance(conflict, dict):
        failures.append("execution_conflict_control must be an object")
    elif conflict.get("exact_match") is not True:
        failures.append("execution_conflict_control.exact_match must be true")
    return failures


def _validate_inputs(
    *,
    qwen: dict[str, Any],
    baseline: dict[str, Any],
    deployment: dict[str, Any],
    backup_restore: dict[str, Any],
    evidence: dict[str, Any],
    hero_incident_id: str,
) -> None:
    failures: list[str] = []
    if qwen.get("proof_type") != "qwen-cloud-smoke" or qwen.get("passed") is not True:
        failures.append("qwen-smoke.json must be a passed qwen-cloud-smoke artifact")
    if baseline.get("proof_type") != "track3-manual-baseline":
        failures.append("track3-baseline.json has wrong proof_type")
    if baseline.get("schema_version") != 2:
        failures.append("track3-baseline.json schema_version must be 2")
    baseline_family = str(baseline.get("baseline", {}).get("incident_family", "")).strip()
    if not baseline_family or "<" in baseline_family:
        failures.append("track3-baseline.json must name a concrete incident family")
    if not _positive_number(baseline.get("speedup_factor")) or baseline.get("speedup_factor", 0) <= 1:
        failures.append("track3-baseline.json must prove speedup_factor > 1")
    yiting_baseline = baseline.get("yiting")
    if not isinstance(yiting_baseline, dict):
        failures.append("track3-baseline.json must include yiting comparison details")
    elif yiting_baseline.get("comparison_scope") == "same-family runsummary runs":
        if not _positive_number(yiting_baseline.get("matched_run_count")):
            failures.append("track3-baseline.json same-family comparison must include matched runs")
        matched_incident_ids = yiting_baseline.get("matched_incident_ids")
        if not matched_incident_ids:
            failures.append("track3-baseline.json same-family comparison must list matched incident ids")
        elif hero_incident_id not in {str(item) for item in matched_incident_ids}:
            failures.append("track3-baseline.json matched runs must include the hero incident")
    elif yiting_baseline.get("comparison_scope") != "runsummary aggregate average":
        failures.append("track3-baseline.json must name its comparison scope")
    checked = baseline.get("track3_requirements_checked")
    if not isinstance(checked, dict) or not checked or not all(value is True for value in checked.values()):
        failures.append("track3-baseline.json must have all Track 3 checks true")
    if deployment.get("proof_type") != "alibaba-ecs-deployment-verification" or deployment.get("passed") is not True:
        failures.append("deployment-verification.json must be a passed deployment artifact")
    targets = deployment.get("targets")
    if not isinstance(targets, dict):
        failures.append("deployment-verification.json missing targets")
    else:
        if targets.get("incident_id") != hero_incident_id:
            failures.append("deployment target incident_id must match the hero incident")
        if targets.get("require_speedup") is not True:
            failures.append("deployment target must require speedup")
        if targets.get("require_public_read_only") is not True:
            failures.append("deployment target must require public read-only mode")
    check_names = _deployment_check_names(deployment)
    if "public chaos disabled" not in check_names:
        failures.append("deployment checks must include public chaos disabled")
    if backup_restore.get("format") != "yiting-backup-restore-v1":
        failures.append("backup-restore.json must use yiting-backup-restore-v1 format")
    if backup_restore.get("project") != "YITING":
        failures.append("backup-restore.json must identify project YITING")
    if backup_restore.get("artifact_class") != "live_backup_restore":
        failures.append("backup-restore.json must be live_backup_restore")
    if backup_restore.get("submission_evidence") is not True or backup_restore.get("verified_live") is not True:
        failures.append("backup-restore.json must be verified live submission evidence")
    if backup_restore.get("passed") is not True:
        failures.append("backup-restore.json must show passed=true")
    backups = backup_restore.get("backups")
    if not isinstance(backups, list):
        failures.append("backup-restore.json must include backup list")
    else:
        backups_by_label = {
            str(item.get("label")): item
            for item in backups
            if isinstance(item, dict)
        }
        for label in ("gateway", "victim"):
            item = backups_by_label.get(label)
            if not item:
                failures.append(f"backup-restore.json missing {label} backup")
                continue
            restore = item.get("restore")
            if item.get("passed") is not True or not isinstance(restore, dict) or restore.get("ok") is not True:
                failures.append(f"backup-restore.json {label} backup restore must pass")
    note = str(backup_restore.get("note", "")).lower()
    if "same-vm backups" not in note or "not total ecs host loss" not in note:
        failures.append("backup-restore.json must disclose same-VM backup limitations")
    if evidence.get("chain_valid") is not True:
        failures.append("hero evidence must have chain_valid=true")
    if evidence.get("incident_id") != hero_incident_id:
        failures.append("hero evidence incident_id must match the requested hero incident")
    if evidence.get("state") != "EXECUTED":
        failures.append("hero evidence final state must be EXECUTED")
    hero_family = str(evidence.get("incident_family", "")).strip()
    if not hero_family or hero_family == "unknown" or "<" in hero_family:
        failures.append("hero evidence must name a concrete incident_family")
    elif (
        baseline_family
        and _normalize_family(hero_family) != _normalize_family(baseline_family)
    ):
        failures.append("hero evidence incident_family must match the baseline incident family")
    cards = evidence.get("cards")
    if not isinstance(cards, list) or len(cards) < 7:
        failures.append("hero evidence must contain at least 7 cards")
    if isinstance(cards, list):
        card_types = {
            str(card.get("card_type", ""))
            for card in cards
            if isinstance(card, dict)
        }
        if "ActionReceipt" not in card_types:
            failures.append("hero evidence must include an ActionReceipt card")
    collaboration = evidence.get("collaboration")
    if not isinstance(collaboration, dict):
        failures.append("hero evidence missing collaboration block")
    else:
        failures.extend(_validate_collaboration_block(collaboration))
    if failures:
        raise FinalProofError("; ".join(failures))


def _md_table(rows: list[tuple[str, Any]]) -> str:
    lines = ["| Field | Value |", "|---|---|"]
    for key, value in rows:
        lines.append(f"| {key} | {value} |")
    return "\n".join(lines)


def render_index(
    *,
    public_url: str,
    hero_incident_id: str,
    qwen: dict[str, Any],
    baseline: dict[str, Any],
    deployment: dict[str, Any],
    backup_restore: dict[str, Any],
    evidence: dict[str, Any],
) -> str:
    summary = baseline.get("yiting", {})
    collaboration = evidence.get("collaboration", {})
    targets = deployment.get("targets", {})
    role_sequence = collaboration.get("role_sequence", [])
    cards = evidence.get("cards", [])
    track3_checks = baseline.get("track3_requirements_checked", {})
    backup_rows = backup_restore.get("backups", [])
    backup_labels = []
    if isinstance(backup_rows, list):
        backup_labels = [
            str(item.get("label"))
            for item in backup_rows
            if isinstance(item, dict) and item.get("passed") is True
        ]
    generated_at = datetime.now(timezone.utc).isoformat()
    speedup = baseline.get("speedup_factor")
    matched_run_ids = baseline.get("yiting", {}).get("matched_incident_ids")
    if isinstance(matched_run_ids, list):
        matched_run_ids_text = ", ".join(str(item) for item in matched_run_ids)
    else:
        matched_run_ids_text = ""
    public_url = public_url.rstrip("/")

    return "\n\n".join([
        "# YITING Final Proof Index",
        (
            "This index ties the final hosted artifacts together for judges. "
            "It is generated only after live Qwen smoke, baseline comparison, "
            "deployment verification, public read-only proof, and hero evidence "
            "chain checks pass. The paired benchmark artifact separately proves "
            "single-agent-vs-society quality gains without claiming speed."
        ),
        _md_table([
            ("Generated at", generated_at),
            ("Primary track", "Track 3: Agent Society"),
            ("Public URL", public_url),
            ("Hero incident", hero_incident_id),
            ("Final state", evidence.get("state")),
            ("Hero incident family", evidence.get("incident_family")),
            ("Evidence URL", f"{public_url}/evidence/{hero_incident_id}"),
            ("Run summary URL", f"{public_url}/stats/runsummary"),
            ("Source package", "dist/yiting-submission-source.zip"),
        ]),
        "## Track 3 Proof",
        _md_table([
            ("Distinct role handoffs", summary.get("total_handoffs")),
            ("Role sequence", " -> ".join(str(role) for role in role_sequence)),
            ("Required roles present", ", ".join(sorted(REQUIRED_SOCIETY_ROLES))),
            ("Hero handoff count", collaboration.get("handoff_count")),
            ("Authorization path", collaboration.get("authorization_path")),
            ("Disagreement events", summary.get("disagreement_events")),
            ("Human interventions", summary.get("human_interventions")),
            ("Recovery verified", summary.get("recovery_verified_count")),
            ("Exact execution match", collaboration.get("execution_conflict_control", {}).get("exact_match")),
            ("Paired quality benchmark", "artifacts/track3-paired-benchmark.json"),
            ("Hosted timing speedup", f"{speedup}x"),
        ]),
        "## Required Track 3 Showcase",
        _md_table([
            ("Distinct capabilities", track3_checks.get("distinct_role_handoffs")),
            ("Task decomposition and handoffs", collaboration.get("handoff_count")),
            ("Hero challenge count", collaboration.get("challenge_count")),
            ("Hero human decisions", collaboration.get("human_decision_count")),
            ("Dialogue or disagreement", track3_checks.get("disagreement_or_revision")),
            ("Human-in-the-loop negotiation", track3_checks.get("human_intervention")),
            ("Execution conflict resolution", collaboration.get("execution_conflict_control", {}).get("exact_match")),
            ("Measured quality and timing proof", track3_checks.get("measured_speedup_over_baseline")),
        ]),
        "## Hosted Artifact Checks",
        _md_table([
            ("Qwen smoke", qwen.get("passed")),
            ("Qwen model", qwen.get("model")),
            ("Baseline incident family", baseline.get("baseline", {}).get("incident_family")),
            ("Baseline seconds", baseline.get("baseline", {}).get("measured_seconds")),
            ("Baseline comparison scope", baseline.get("yiting", {}).get("comparison_scope")),
            ("Baseline matched runs", baseline.get("yiting", {}).get("matched_run_count")),
            ("Baseline matched incident IDs", matched_run_ids_text or "n/a"),
            ("Deployment passed", deployment.get("passed")),
            ("Backup restore proof", backup_restore.get("passed")),
            ("Backup labels", ", ".join(backup_labels)),
            ("Requires speedup", targets.get("require_speedup")),
            ("Public read-only required", targets.get("require_public_read_only")),
            ("Public chaos disabled check", "public chaos disabled" in _deployment_check_names(deployment)),
            ("Evidence chain valid", evidence.get("chain_valid")),
            ("Evidence cards", len(cards)),
        ]),
        "## Weighted Judge Score Map",
        _md_table([
            (
                "Stage One viability",
                "Track 3 Agent Society + live Qwen smoke + Alibaba ECS deployment verification",
            ),
            (
                "Innovation & AI Creativity — 30%",
                "Custom agent skills, Qwen-backed role society, challenge loop, human revision loop",
            ),
            (
                "Technical Depth & Engineering — 30%",
                "SHA-256 evidence chain, nonce-bound authorization, exact-envelope execution, recovery verification",
            ),
            (
                "Problem Value & Impact — 25%",
                "Governed emergency change control, false-alarm handling, paired quality gains, measured same-family timing when configured",
            ),
            (
                "Presentation & Documentation — 15%",
                "Landing page, dashboard replay, evidence export, judge packet, source package",
            ),
            (
                "Blog Post Prize",
                "docs/BLOG_POST.md explains the agent-society design and impact narrative",
            ),
        ]),
        "## Reviewer Cross-Checks",
        _md_table([
            (
                "Track choice",
                "Track 3 is primary; Track 4 remediation is the outcome, not the judged behavior.",
            ),
            (
                "Qwen use",
                f"Live Qwen smoke passed: {qwen.get('passed')} with model {qwen.get('model')}.",
            ),
            (
                "Custom skill proof",
                "/agent-skills is an inspectable MCP-style registry and review manifest, not a network MCP server.",
            ),
            (
                "Not mocked",
                f"Hero evidence {hero_incident_id} reached {evidence.get('state')} with chain_valid={evidence.get('chain_valid')}.",
            ),
            (
                "Baseline honesty",
                "The paired benchmark does not claim speed; speedup is tied to artifacts/track3-baseline.json and a measured same-family baseline.",
            ),
            (
                "Public cost control",
                f"Public read-only judge mode required: {targets.get('require_public_read_only')}; chaos disabled check is recorded above.",
            ),
            (
                "Execution safety",
                "Exact-envelope execution, nonce-bound approval, duplicate suppression, and recovery verification gate the ActionReceipt.",
            ),
            (
                "Persistence safety",
                "artifacts/live/backup-restore.json proves gateway and victim SQLite backups were restore-tested before recording.",
            ),
        ]),
        "## Submission Requirement Cross-Checks",
        _md_table([
            (
                "Installability",
                "`docs/INSTALL_AND_RUN.md` gives source-package install, local verification, and hosted deployment commands.",
            ),
            (
                "Public open-source repository",
                "`docs/PUBLIC_REPOSITORY.md` lists visibility, MIT license, About-panel, topics, and no-secret checks.",
            ),
            (
                "Alibaba Cloud proof",
                "`docs/ALIBABA_CLOUD_PROOF.md`, `deploy/alibaba-ecs/README.md`, and this proof index tie code links to hosted ECS verification.",
            ),
            (
                "Architecture diagram",
                "`docs/ARCHITECTURE.md` documents the Qwen Cloud, Gateway, evidence ledger, dashboard, and agent-society flow.",
            ),
            (
                "Demo media compliance",
                "`docs/DEMO_SCRIPT.md` and `docs/THIRD_PARTY_COMPLIANCE.md` require a public video under 3 minutes with only project UI, proof artifacts, and permitted media.",
            ),
            (
                "Final submission runbook",
                "`docs/FINAL_SUBMISSION_CHECKLIST.md` orders recording, judge-mode lock-down, public-link finalization, hosted proof, and strict audit.",
            ),
        ]),
        "## Files To Attach Or Link",
        "\n".join([
            "- `artifacts/qwen-smoke.json`",
            "- `artifacts/track3-paired-benchmark.json`",
            "- `artifacts/track3-baseline.json`",
            "- `artifacts/deployment-verification.json`",
            "- `artifacts/live/backup-restore.json`",
            "- `artifacts/hero-evidence.json`",
            "- `artifacts/final-proof-index.md`",
            "- `dist/yiting-submission-source.zip`",
            "- `docs/INSTALL_AND_RUN.md`",
            "- `docs/PUBLIC_REPOSITORY.md`",
            "- `docs/ARCHITECTURE.md`",
            "- `docs/ALIBABA_CLOUD_PROOF.md`",
            "- `docs/THIRD_PARTY_COMPLIANCE.md`",
            "- `docs/FINAL_SUBMISSION_CHECKLIST.md`",
        ]),
        "## Judge Route",
        "\n".join([
            "1. Open the landing page.",
            "2. Open `/agent-skills` for distinct capabilities.",
            "3. Open the hero evidence URL and verify `chain_valid: true`.",
            "4. Inspect `collaboration.role_sequence` for task decomposition.",
            "5. Inspect challenge/rejection counts for disagreement resolution.",
            "6. Inspect `execution_conflict_control.exact_match` for execution conflict control.",
            "7. Open `artifacts/track3-paired-benchmark.json` for quality gains, then `/stats/runsummary` for hosted timing speed only if configured.",
        ]),
    ]) + "\n"


def build_final_proof_index(
    *,
    public_url: str,
    hero_incident_id: str,
    artifact_dir: Path = DEFAULT_ARTIFACT_DIR,
    hero_evidence_json: Path = DEFAULT_HERO_EVIDENCE,
    output_md: Path = DEFAULT_OUTPUT,
    fetch_evidence: bool = True,
) -> Path:
    public_url = public_url.strip().rstrip("/")
    hero_incident_id = hero_incident_id.strip()
    if not public_url.startswith("https://"):
        raise FinalProofError("--public-url must be an absolute https:// URL")
    if not hero_incident_id:
        raise FinalProofError("--hero-incident-id is required")

    qwen = _read_json(artifact_dir / "qwen-smoke.json")
    baseline = _read_json(artifact_dir / "track3-baseline.json")
    deployment = _read_json(artifact_dir / "deployment-verification.json")
    backup_restore = _read_json(artifact_dir / "live" / "backup-restore.json")
    if fetch_evidence:
        evidence = _fetch_json(f"{public_url}/evidence/{hero_incident_id}")
        hero_evidence_json.parent.mkdir(parents=True, exist_ok=True)
        hero_evidence_json.write_text(
            json.dumps(evidence, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    else:
        evidence = _read_json(hero_evidence_json)

    _validate_inputs(
        qwen=qwen,
        baseline=baseline,
        deployment=deployment,
        backup_restore=backup_restore,
        evidence=evidence,
        hero_incident_id=hero_incident_id,
    )
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_md.write_text(
        render_index(
            public_url=public_url,
            hero_incident_id=hero_incident_id,
            qwen=qwen,
            baseline=baseline,
            deployment=deployment,
            backup_restore=backup_restore,
            evidence=evidence,
        ),
        encoding="utf-8",
    )
    return output_md


def main() -> int:
    parser = argparse.ArgumentParser(description="Build final YITING proof index")
    parser.add_argument("--public-url", default=os.getenv("PUBLIC_BASE_URL", ""))
    parser.add_argument("--hero-incident-id", default=os.getenv("HERO_INCIDENT_ID", ""))
    parser.add_argument("--artifact-dir", type=Path, default=DEFAULT_ARTIFACT_DIR)
    parser.add_argument("--hero-evidence-json", type=Path, default=DEFAULT_HERO_EVIDENCE)
    parser.add_argument("--output-md", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--no-fetch-evidence",
        action="store_true",
        help="read --hero-evidence-json instead of fetching from the public deployment",
    )
    args = parser.parse_args()

    try:
        output = build_final_proof_index(
            public_url=args.public_url,
            hero_incident_id=args.hero_incident_id,
            artifact_dir=args.artifact_dir,
            hero_evidence_json=args.hero_evidence_json,
            output_md=args.output_md,
            fetch_evidence=not args.no_fetch_evidence,
        )
    except FinalProofError as exc:
        print(f"final proof index failed: {exc}")
        return 2
    print(f"Final proof index written: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
